const fs = require("fs");
async function getWordleAnswer(date: Date) {
  const dateString = toDateStr(date);
  const wordleUrl = `https://www.nytimes.com/svc/wordle/v2/${dateString}.json`;
  const result = await fetch(wordleUrl);
  return (await result.json()).solution as string;
}

function toDateStr(date: Date) {
  const offset = date.getTimezoneOffset();
  const offsetDate = new Date(date.getTime() - offset * 60 * 1000);
  return offsetDate.toISOString().split("T")[0];
}

(async () => {
  const currentDate = new Date();
  const dayinMS = 24 * 60 * 60 * 1000;

  const answers: Record<string, string> = {};
  for (let i = -1; i < 29; i++) {
    const newDate = new Date(currentDate.getTime() + i * dayinMS);
    console.log(`Doing ${toDateStr(newDate)}`);
    answers[toDateStr(newDate)] = await getWordleAnswer(newDate);
  }

  fs.writeFileSync(
    "lib/wordleAnswers/wordleAnswers.ts",
    "// generated by `yarn run generate-wordle-answers`\n" +
      "export const wordleAnswers : Record<string,string> = " +
      JSON.stringify(answers, null, 2)
  );
  console.log(answers);
})();
